### ISSUE TITLE
The `x-axis` RulersScale is smaller or half rendered compared to `y-axis`

### ISSUE THREAD

**Issue by hasnentai** [GeekyAnts/geekyants_flutter_charts#10]
The `x-axis` RulersScale is smaller or half rendered compared to `y-axis`

**Comment by Gayathri-GA** [comment]
@hasnentai  Fixed #10 
[Link to commit fixing this issue](https://github.com/GeekyAnts/geekyants_flutter_charts/commit/b9d3c858a6dd72ba16bd552ec45da1c354927078)
